#!/usr/bin/env bash
# gc-vault-sync — Direction A: render the soundit-dev city status into Charlie's
# Obsidian vault and commit+push it. Deterministic, no AI. Resilient: never
# leaves status.md empty and never crashes the timer; on gc/data failure it
# writes a clear stale/error marker instead.
#
# Single git committer for wiki/sound-psa/soundit-dev/ — it `git add`s the WHOLE
# folder, so the mayor's brain/ notes (Direction B) ride along on each cycle.
# It writes ONLY status.md; it never regenerates soundit-dev.md or brain/_index.md.
#
# Usage: gc-vault-sync.sh [--dry-run]   (--dry-run prints to stdout; no write/commit)
set -uo pipefail

VAULT="/home/charlie/coutts-vault"
DIR="$VAULT/wiki/sound-psa/soundit-dev"
OUT="$DIR/status.md"
RIG="soundit-psa"
DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

ERRORS=""
note_err() { ERRORS="${ERRORS:+$ERRORS; }$1"; }

# Run a gc/bd query with a timeout; strip the noisy native_store WARN lines.
# Echoes output (possibly empty); records an error on failure/timeout.
q() {
  local label="$1"; shift
  local out
  if ! out=$(timeout 25 "$@" 2>/dev/null); then
    note_err "$label"
    return 1
  fi
  printf '%s' "$out" | grep -v 'native_store_unavailable'
}

# Pacific time to match the rest of Charlie's vault (relay note); both forms are valid ISO-8601.
now_iso=$(TZ='America/Los_Angeles' date -Iseconds)
now_human=$(TZ='America/Los_Angeles' date '+%Y-%m-%d %H:%M %Z')

# --- gather (each guarded) ---
sessions=$(q "sessions" gc session list)
active_count=$(printf '%s\n' "$sessions" | awk 'NR>1 && $3=="active"' | grep -c . || true)
asleep_count=$(printf '%s\n' "$sessions" | awk 'NR>1 && $3=="asleep"' | grep -c . || true)
# active sessions: template + state only (drop churning age/last-active so the
# digest is stable run-to-run; the commit gate below depends on that stability).
active_tbl=$(printf '%s\n' "$sessions" | awk 'NR==1 || $3=="active" {printf "%-30s %s\n", $2, $3}')

riglist=$(q "rigs" gc rig list)
# Compact to one line per rig (relay note: raw `gc rig list` is verbose).
rigs_compact=$(printf '%s\n' "$riglist" | awk '
  /^[[:space:]]{2}[^[:space:]].*:$/ { if (cur!="") print cur; cur=$0; sub(/^[[:space:]]+/,"",cur); sub(/:$/,"",cur); next }
  /Prefix:/         { cur=cur"  prefix="$2 }
  /Path:/           { cur=cur"  "$2 }
  /Default branch:/ { cur=cur"  @"$3 }
  END { if (cur!="") print cur }
')

# soundit-psa work (psa-) — filter ephemeral review/sling/order/nudge wisps (noise)
psa_ready_json=$(q "psa-ready" gc bd ready --rig "$RIG" --json --limit 40)
psa_clean=$(printf '%s' "$psa_ready_json" | jq -c '[.[]? | select((.title|test("^(sling-|order:|nudge:|wisp:)";"i"))|not) | select((.title|test("Read the review assignment";"i"))|not)]' 2>/dev/null)
psa_ready=$(printf '%s' "$psa_clean" | jq -r '.[] | "\(.id)  P\(.priority)  \(.title)"' 2>/dev/null | head -8)
psa_ready_n=$(printf '%s' "$psa_clean" | jq -r 'length' 2>/dev/null)
psa_wip_json=$(q "psa-wip" gc bd list --rig "$RIG" --status in_progress --json --limit 8)
psa_wip=$(printf '%s' "$psa_wip_json" | jq -r '.[]? | "\(.id)  \(.title)"' 2>/dev/null)
psa_wip_n=$(printf '%s' "$psa_wip_json" | jq -r '.[]?.id' 2>/dev/null | grep -c . || true)

# HQ coordination (ga-), filtering ephemeral order:/nudge:/wisp churn
hq_ready_json=$(q "hq-ready" gc bd ready --json --limit 20)
hq_ready=$(printf '%s' "$hq_ready_json" | jq -r '.[]? | select((.title|test("^(order:|nudge:|wisp:)"))|not) | "\(.id)  \(.title)"' 2>/dev/null | head -5)

# P1s in the rig backlog = needs attention
psa_p1=$(printf '%s' "$psa_clean" | jq -r '.[] | select(.priority==1) | "\(.id)  \(.title)"' 2>/dev/null)

# --- render ---
render() {
  cat <<EOF
---
type: dashboard
title: "soundit-dev — city status"
tags: [gas-city, dashboard, auto-generated]
updated: $now_iso
---

> [!warning] Auto-generated by \`gc-vault-sync\` — do not edit by hand.

# soundit-dev — city status

_Last synced: $now_human._
EOF
  if [ -n "$ERRORS" ]; then
    cat <<EOF

> [!warning] STALE / PARTIAL — some \`gc\` data was unavailable at sync time ($ERRORS). Showing last-known/partial below.
EOF
  fi
  cat <<EOF

The [[soundit-dev]] city orchestrating [[Sound PSA]]. (Bead ids/agent names below are plain text — see [[beads]] for the live tracker.)

## Health
- Control plane sessions: **${active_count:-?} active**, ${asleep_count:-?} asleep.
\`\`\`text
${active_tbl:-(session data unavailable)}
\`\`\`

## Open work — Sound PSA
- Ready: **${psa_ready_n:-?}** · In progress: **${psa_wip_n:-0}**
EOF
  if [ -n "$psa_ready" ]; then printf '\nReady (top):\n```text\n%s\n```\n' "$psa_ready"; fi
  if [ -n "$psa_wip" ]; then printf '\nIn progress:\n```text\n%s\n```\n' "$psa_wip"; fi

  if [ -n "$psa_p1" ]; then printf '\n## Needs attention\n```text\n%s\n```\n' "$psa_p1"; fi

  if [ -n "$hq_ready" ]; then printf '\n## Coordination (HQ)\n```text\n%s\n```\n' "$hq_ready"; fi

  printf '\n## Rigs\n```text\n%s\n```\n' "${rigs_compact:-(rig data unavailable)}"
}

if [ "$DRY_RUN" = 1 ]; then
  render
  [ -n "$ERRORS" ] && echo "# (dry-run note: errors = $ERRORS)" >&2
  exit 0
fi

# --- render to temp ---
TMP=$(mktemp)
render > "$TMP"
if [ ! -s "$TMP" ]; then echo "gc-vault-sync: refusing to write empty status.md" >&2; rm -f "$TMP"; exit 1; fi

# --- refresh status.md only on SUBSTANTIVE change (ignore the volatile timestamp
#     lines) OR if the last sync is >6h old (heartbeat: keeps 'last synced' current
#     + proves liveness). This avoids ~100 timestamp-only commits/day in the vault. ---
strip_ts() { grep -vE '^updated:|^_Last synced:'; }
refresh=1
if [ -f "$OUT" ] && diff -q <(strip_ts <"$TMP") <(strip_ts <"$OUT") >/dev/null 2>&1; then refresh=0; fi
last_ct=$(cd "$VAULT" 2>/dev/null && git log -1 --format=%ct -- wiki/sound-psa/soundit-dev/status.md 2>/dev/null)
last_ct=${last_ct:-0}
[ $(( $(date +%s) - last_ct )) -ge 21600 ] && refresh=1   # 6h heartbeat
if [ "$refresh" = 1 ]; then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi

# --- commit + push the WHOLE folder (so mayor brain/ notes ride along even when
#     status.md itself didn't change). Single committer for soundit-dev/. ---
cd "$VAULT" || { echo "gc-vault-sync: vault missing" >&2; exit 1; }
git add wiki/sound-psa/soundit-dev
if git diff --cached --quiet; then
  echo "gc-vault-sync: nothing to commit (no substantive change, no brain/ updates)"
  exit 0
fi
git -c core.autocrlf=false commit -q -m "soundit-dev: status sync $now_iso" || { echo "gc-vault-sync: commit failed" >&2; exit 1; }
git pull --rebase --autostash --quiet origin main 2>&1 | tail -1
if git push --quiet origin main 2>&1 | tail -3; then
  echo "gc-vault-sync: pushed $now_iso"
else
  echo "gc-vault-sync: push failed (will retry next cycle)" >&2
fi
